### ISSUE TITLE
OPPD to store measurements in esmond

### ISSUE THREAD

**Issue by arlake228** [perfsonar/oppd#1]
_From @arlake228 on March 14, 2015 12:38_

Original [issue 1003](https://code.google.com/p/perfsonar-ps/issues/detail?id=1003) created by arlake228 on 2014-10-16T12:51:56.000Z:

Currently, OPPD measurements can only be stored into the MDM SQL MA.  With the new MA available, we need to store the measurements in it.

See the following information:
- http://software.es.net/esmond/
- MeasurementArchiveClientGuide
- MeasurementArchivePerlAPI

Ideally both storage to the local esmond instance or to a remote instance should be available through configuration.

_Copied from original issue: perfsonar/project#1001_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1003#c1) originally posted by arlake228 on 2014-10-16T12:53:27.000Z:

Proper link to he PerlAPI: https://code.google.com/p/perfsonar-ps/wiki/MeasurementArchivePerlAPI

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=1003#c2) originally posted by arlake228 on 2015-01-27T15:26:19.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
i think this is done. can we close it?

**Comment by laeti-tia** [comment]
No, this is not done yet, postponing to 3.6.

**Comment by HakanCalimFau** [comment]
Hi,
have commited the first version of support for OWAMP and BWCTL MP.  Need to be tested. There are small changes in the protocol. Adjusted the measurement result for storing in esmond. PSUI request RAW from OWAMP MP. OWAMP MP use now summary for storage and this is actually the default response. For BWCTL MP I changed the bandwith unit from Mbits/s to KBits/s to have more details. This should be also adjusted n psUI.

**Comment by HakanCalimFau** [comment]
Hi all,

I checked with:
http://ps-ui-test.qalab.geant.net/perfsonar-ui/login.jsp

and OWAMP MP and BWCTL MP works. Chose my development endpoint for testing. It is RRZE Hakan DEV for both. In case of BWCTL it seems no changes are needed. And the measurement results will be stored in esmond.

If we also want to store measurement with OWAMP MPpsUI should send a request with output type machine_readable. At the moment it sends raw. Measuremnt with raw results are not stored at the moment. I didn't found an example with storing raw measurement results.

In the machine_readable  output there is a field histogram_delay. I think this can be used for diplaying the measurement. 

Please check it as well if everything is ok! Thanks.

Best regards,
Hakan

**Comment by HakanCalimFau** [comment]
Ivan and I checked BWCTL MP and it seems everything OK with psUI. For OWAMP MP we had a idea to get RAW and machine_readable at the same time. I will check this. Maybe then no changes are needed in psUI.

**Comment by igarny** [comment]
Tests were produced.
An issue was identified.
A fix was provided
Additional test were run.

**Comment by arlake228** [comment]
Can this issue be closed or is there more to be done?

**Comment by laeti-tia** [comment]
Yes, this is done.
