### ISSUE TITLE
Better iperf3 support

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/oppd#2]
OPPD need to be able to parse the output of iperf3.  iperf3 will be the default measurement tool used by bwctl in the upcoming 3.5 toolkit release (bwctl 2.0).

There is currently at least one issue with the summary/average measurement for which iperf3 is giving 2 different values, one from the receiver side, one from the sender side (iperf2 was only presenting one summary/average measurement).  For psUI consumption, it would be good that the 2 average measurements can be distinguishable in the XML answer, maybe by adding an attribute to those measurements?

Ivan also has a query about the retries.

**Comment by igarny** [comment]
So in fact the inquiry here is about the presentation of the information as a whole.
Since both instances (sender & receiver) show different numbers on the speed of the transfer. 
1) Which one is going to be presented. To me most reasonable seems to be the one of the receiver since the intermediate results are taken from him.

2) And also how do we present the information about the retries?

I would assume such discussions have happened already on the design for the measurement archive and visualization.

**Comment by laeti-tia** [comment]
For 1) Rade said he could present average measurements for both the sender and the receiver in the psUI, adding a new line to the graph.  I think that is the most valuable as it presents the same information as one would get from the CLI.  But this means that the psUI need to be able to know which summary/average measurement is for each side.

For 2) I'm not sure, what is your suggestion?

**Comment by igarny** [comment]
on 2) my suggestion is to export the information to pS UI

Number of retries could be also juts a bar from the bottom of the graph, but it would also be nice, if it is an optional graph.

**Comment by arlake228** [comment]
For regular testing we use the receiver side stats unless a stats is only available on the sender side. See code snippet below:

```
        $summary_overall_obj->throughput($received_summary->{bits_per_second}) if $received_summary->{bits_per_second};
        $summary_overall_obj->jitter($received_summary->{jitter_ms}) if $received_summary->{jitter_ms};
        $summary_overall_obj->packets_sent($received_summary->{packets}) if defined $received_summary->{packets};
        $summary_overall_obj->packets_lost($received_summary->{lost_packets}) if defined $received_summary->{lost_packets};
        $summary_overall_obj->retransmits($sent_summary->{retransmits}) if defined $sent_summary->{retransmits};
        $summary_overall_obj->snd_cwnd($sent_summary->{snd_cwnd}) if defined $sent_summary->{snd_cwnd};
```

**Comment by igarny** [comment]
I would like to rephrase my wording on the comment for 2)
Number of retries could also be just a bar from the bottom of the graph, but it would be nice if it is presented optionally on the plot. (so if one is not interested to be able to hide it)

**Comment by RockyMM** [comment]
As an illustration, this is the response from OPPD I'm seeing. https://slack-files.com/T03NBUPHD-F065S5T7A-d9cc8ac212

Only thing that tells me that something is summary is that it's duration is equal or longer than the test itself, which really is ... bad decision. I would like to have separate summary element(s) with all parameters that Andy had listed in his response.

About retries, is this the same as "retransmits"? If so - is the chart really good place for this, since it would always be one bar stretching through entire chart? Or I am mistaken and retries are available for each report.

**Comment by HakanCalimFau** [comment]
OPPD supports at the moment iperf and not iperf3 therefore some values 
from iperf3 result not available in OPPD at the moment.

Here is an example output from commandline for iperf what OPPD can parse:

```
2 ~]$  bwctl -s 131.188.81.33 -c 137.164.30.5 -i 6 -t 30
bwctl: Using tool: iperf
bwctl: 37 seconds until test results available

RECEIVER START
------------------------------------------------------------
Server listening on TCP port 5257
Binding to local address 137.164.30.5
TCP window size: 87380 Byte (default)
------------------------------------------------------------
[ 15] local 137.164.30.5 port 5257 connected with 131.188.81.33 port 41921
[ ID] Interval       Transfer     Bandwidth
[ 15]  0.0- 6.0 sec  33488992 Bytes  44651989 bits/sec
[ 15]  6.0-12.0 sec  47168544 Bytes  62891392 bits/sec
[ 15] 12.0-18.0 sec  45945456 Bytes  61260608 bits/sec
[ 15] 18.0-24.0 sec  47264112 Bytes  63018816 bits/sec
[ 15] 24.0-30.0 sec  45909952 Bytes  61213269 bits/sec
[ 15]  0.0-30.0 sec  219938816 Bytes  58565137 bits/sec
[ 15] MSS size 1448 bytes (MTU 1500 bytes, ethernet)

RECEIVER END
```

the iperf3:

```
~]$  bwctl -T iperf3 -s 131.188.81.33 -c 137.164.30.5 -i 6 -t 30
bwctl: Using tool: iperf3
bwctl: 38 seconds until test results available

SENDER START
Connecting to host 137.164.30.5, port 5140
[ 15] local 131.188.81.33 port 39170 connected to 137.164.30.5 port 5140
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[ 15]   0.00-6.00   sec  30.8 MBytes  43.0 Mbits/sec    0   1.47 MBytes
[ 15]   6.00-12.00  sec  44.4 MBytes  62.1 Mbits/sec    0   1.47 MBytes
[ 15]  12.00-18.00  sec  42.9 MBytes  60.0 Mbits/sec    0   1.47 MBytes
[ 15]  18.00-24.00  sec  44.2 MBytes  61.7 Mbits/sec    0   1.47 MBytes
[ 15]  24.00-30.00  sec  41.1 MBytes  57.4 Mbits/sec  354   1.14 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[ 15]   0.00-30.00  sec   203 MBytes  56.9 Mbits/sec 354             sender
[ 15]   0.00-30.00  sec   203 MBytes  56.8 Mbits/sec                  
receiver

iperf Done.

SENDER END
```

Here we have a additional column Retr  Cwnd and on the last two average 
lines the information about sender and receiver. These needs a 
adjustment in the schema data.

Additionally we should decide if this fields on iperf result should be 
blank or should not be used. But this all needs more work.

Am 15.06.2015 12:53, schrieb Rade Martinović:

**Comment by igarny** [comment]
Then I suggest keeping the same labels of the fields as from Andy's comment.
retransmits and snd_cwnd
I would prefer and even insist on keeping and presenting the intermediate values from the measurement as presented by the bwctl output.
Reason is: that if data in Esmond is seen for long term assessment, capacity planning and proactive monitoring, pS UI should be providing a solution for precise diagnostic measurements, which try to prove and see what the problem in detail. It should be a replacement for my console operations on the perfSONAR MP toolkit.

**Comment by RockyMM** [comment]
> Additionally we should decide if this fields on iperf result should be blank or should not be used. But this all needs more work.

Why not devise new schema with different namespace? 

While we're at it, I would like summaries/averages to have different datatype than regular data or some kind of differentiation. I see from iperf3 output that all summaries/averages are present after "---------------------", so it would not make it that difficult to recognize them and put them in to oppd message separate from the rest of the data.

**Comment by RockyMM** [comment]
We've had quick chat about this request today. Here's my take refined just a tiny bit further:

When supporting iperf3 output I would like a different schema to be used so that:
1) all fields that are reported by iperf3 are present in the oppd output (Retr and Cwnd included)
2) summaries are reported different that interval data (this is really important)
3) it would be nice to have the number of seconds until results since that would improve user experience; this would require reengineering how requests are made to oppd when using iperf than using iperf3 - since probably there would have to be initial response with just number of seconds and then another request for full data with the response for actual data.  

But I am all for these changes, given the value we could present to the user.

**Comment by HakanCalimFau** [comment]
OK here is the actuall schema for bwctl.

Am 23.06.2015 15:00, schrieb Rade Martinović:

**Comment by RockyMM** [comment]
@HakanCalimFau I am sorry, I don't see the schema. Can you please post it again, or just paste it inline in the comment?

**Comment by RockyMM** [comment]
Hakan sent me the schema in the private message. Not to be lost, here it is :

```
# ##############################################################
# 
# File:         bwctl.rnc - 
# Version:      $Id$
# Purpose:      
# Reference:    http://books.xmlschemata.org/relaxng/page2.html
# 
# ##############################################################


# ##############################################################
# Namespace definitions
# ##############################################################
namespace nmwg = "http://ggf.org/ns/nmwg/base/2.0/"
namespace bwctl = "http://ggf.org/ns/nmwg/tools/bwctl/2.0/"
namespace nmwgtopo3 = "http://ggf.org/ns/nmwg/topology/base/3.0/"
namespace nmwgt = "http://ggf.org/ns/nmwg/topology/2.0/"


# ##############################################################
# Include additional functionality from other files
# ##############################################################
include "nmtopo.rnc"
include "nmtopo_ver3.rnc"
include "result.rnc"
include "nmbase.rnc" {
        Metadata |= BwctlMetadata
        Data |= BwctlData
}


# ##############################################################
# Metadata is the 'data' that describes physical measurements. 
# Metadata can be something such as a physical address, or 
# a geographical location; any form of static, re-usable 
# designation.  It is important to note that the subject
# namespace and parameters namespace MUST match (or the parameters
# can be a generic NMWG) or bad things will occur.
#
# Example: 
# 
# <nmwg:metadata id="REQUIRED_ID" 
#                metadataIdRef="OPTIONAL_REFERENCE_ID"
#                xmlns:nmwg="http://ggf.org/ns/nmwg/base/2.0/">
# 
#   <!-- TBD OPTIONAL SUBJECT -->
# 
#   <!-- TBD OPTIONAL PARAMETERS -->
#
#   <!-- TBD OPTIONAL EVENTTYPE -->
# 
#   <!-- TBD OPTIONAL KEY -->
#  
#   <!-- ANY OPTIONAL (MULTIPLE) ELEMENT IN ANY NAMESPACE --> 
#
# </nmwg:metadata>
# 
# ##############################################################
BwctlMetadata =
        element nmwg:metadata {
                Identifier &
                MetadataIdentifierRef? &
                (
                        BwctlMetadataContent |
                        anyElement*
                )
        }

BwctlMetadataBlock =
        BwctlSubject? &
        (
                BwctlParameters |
                Parameters
        )?

BwctlMetadataContent =
        (
                BwctlMetadataBlock
        ) &
        EventType? &
        Key?


# ##############################################################
# Redefined bwctl subject allows only an endPoint or endPointPair, 
# and the two id attributes.    
#
# Example: 
# 
# <bwctl:subject id="REQUIRED_ID" 
#               metadataIdRef="OPTIONAL_REFERENCE_ID"
#               xmlns:nmwg="http://ggf.org/ns/nmwg/tools/bwctl/2.0/">
# 
#   <nmwgtopo:endPointPair xmlns:nmwgtopo="http://ggf.org/ns/nmwg/topology/2.0/">
# 
#     <nmwgtopo:src type="REQUIRED_TYPE" value="REQUIRED_VALUE" 
#                   port="OPTIONAL_PORT"/>
# 
#     <nmwgtopo:dst type="REQUIRED_TYPE" value="REQUIRED_VALUE" 
#                   port="OPTIONAL_PORT"/>
#  
#   </nmwgtopo:endPointPair>
#  
#  
#   <!-- OR -->
#  
#  
#   <nmtl4:endPointPair xmlns:nmtl4="http://ggf.org/ns/nmwg/topology/l4/3.0/">
#  
#     <nmtl4:endPoint role="OPTIONAL_ROLE" port="OPTIONAL_PORT" 
#                     protocol="OPTIONAL_PROTOCOL">
#  
#       <nmtl4:address value="REQUIRED_VALUE" type="REQUIRED_TYPE"/>
#  
#     </nmtl4:endPoint>
#  
#     <nmtl4:endPoint role="OPTIONAL_ROLE" port="OPTIONAL_PORT" 
#                     protocol="OPTIONAL_PROTOCOL">
#  
#       <nmtl4:address value="REQUIRED_VALUE" type="REQUIRED_TYPE"/>
#  
#     </nmtl4:endPoint>
#  
#   </nmtl4:endPointPair>
#  
#
#   <!-- OR -->  
# 
# 
#   <nmwgtopo:endPoint port="OPTIONAL_PORT" 
#                      value="REQUIRED_VALUE" 
#                      type="REQUIRED_TYPE"
#                      xmlns:nmwgtopo="http://ggf.org/ns/nmwg/topology/2.0/"/>
#
#
#   <!-- OR -->
#  
#  
#   <nmtl4:endPoint role="OPTIONAL_ROLE" port="OPTIONAL_PORT" 
#                   protocol="OPTIONAL_PROTOCOL" 
#                   xmlns:nmtl4="http://ggf.org/ns/nmwg/topology/l4/3.0/">
#  
#     <nmtl4:address value="REQUIRED_VALUE" type="REQUIRED_TYPE"/>
#  
#   </nmtl4:endPoint>
#  
# </ping:subject>
#
# ##############################################################
BwctlSubject =
        element bwctl:subject {
                Identifier &
                MetadataIdentifierRef? &
                (
                        (
                                EndpointPair |
                                L4EndpointPair
                        ) |
                        (
                                Endpoint |
                                L4Endpoint
                        )                        
                )
        }


# ##############################################################
# This is simply the regular method of doing parameters with an
# enumeration to limit what 'names' are accepted and an outer
# bwctl: namespace for the parameters.
#
# Example: 
# 
# <ping:parameters id="REQUIRED_ID" 
#                   xmlns:nmwg="http://ggf.org/ns/nmwg/tools/bwctl/2.0/">
# 
#   <nmwg:parameter name="REQUIRED_ENUM_NAME" value="OPTIONAL_VALUE"
#                   xmlns:nmwg="http://ggf.org/ns/nmwg/base/2.0/">
# 
#     <!-- ANY TEXT, (IF YOU DID NOT USE THE VALUE ATTRIBUTE) -->
# 
#   </nmwg:parameter>
#  
#   <!-- MORE PARAMETERS -->
#   
# </ping:parameters>
# 
# ##############################################################
BwctlParameters =
        element bwctl:parameters {
                Identifier &
                BwctlParameter+
        }

BwctlParameter =
        element nmwg:parameter {
                attribute name { "duration" | "advisoryWindowsize" |
                                 "scheduleInterval" | "latest" |
                                 "numberOfTests" | "alpha" 
                } &
                (
                        attribute value { xsd:int } |
                        xsd:int
                )
        }



# ##############################################################
# The data block is complex, and has the potential to contain
# many things.  The data block can be used to return a metadata
# block from a request, commonTime or datum elements, keys, 
# or something that we have perhaps not defined as of yet.  
#
# Example: 
# 
# <nmwg:data id="REQUIRED_ID" 
#            metadataIdRef="OPTIONAL_REFERENCE_ID" 
#            xmlns:nmwg="http://ggf.org/ns/nmwg/base/2.0/">
# 
#   <!-- OPTIONAL (MULTIPLE) METADATA -->
# 
#           <!-- OR -->
#
#   <!-- TBD OPTIONAL (MULTIPLE) COMMON TIME ELEMENTS AND 
#        OPTIONAL (MULTIPLE) RESULT DATUM ELEMENTS-->
# 
#           <!-- OR -->
#  
#   <!-- TBD OPTIONAL (MULTIPLE) RESULT DATUM ELEMENTS -->
# 
#           <!-- OR -->
#  
#   <!-- OPTIONAL (MULTIPLE) KEY ELEMENTS -->
#   
# </nmwg:data>
# 
# ##############################################################
BwctlData =
        element nmwg:data {
                Identifier &
                MetadataIdentifierRef? &
                (
                        (
                                Metadata* |
                                BwctlMetadata*
                        ) |
                        (
                                BwctlCommonTime+ &
                                ResultDatum*
                        ) |
                        ResultDatum* |
                        Key*
                )
        }


# ##############################################################
# CommonTime is used a a shortcut able to 'factor out' a frequently
# occurring time range that a bunch of datum (or other) elements
# might share, thus reducing complexity of XML representation.  
# CommonTime is similar to the other NMWG time stamps (from 
# nmtime.rnc) in its potential time representations.
#
# Example: 
# 
# <nmwg:commonTime type="REQUIRED_TYPE" value="OPTIONAL_VALUE"
#                  duration="OPTIONAL_DURATION" 
#                  inclusive="OPTIONAL_INCLUSIVE_FLAG"
#                  xmlns:nmwg="http://ggf.org/ns/nmwg/base/2.0/">
# 
#   <!-- TBD OPTIONAL START TIME ELEMENT (USE END TIME OR DURATION) -->
#  
#   <!-- TBD OPTIONAL END TIME ELEMENT (ONLY WITH START TIME) -->
#  
#   <!-- TBD OPTIONAL TIME VALUE ELEMENT (USE IF NO VALUE ATTRIBUTE) -->
#  
#   <!-- TBD OPTIONAL (MULTIPLE) RESULT DATUM ELEMENTS -->
#
# </nmwg:commonTime>
# 
# ##############################################################
BwctlCommonTime =
        element nmwg:commonTime {
                Type &
                (
                        TimeStamp |
                        (
                                StartTime &
                                (
                                        EndTime |
                                        Duration
                                )
                        )
                ) &
                ResultDatum*
        }
```

**Comment by HakanCalimFau** [comment]
And what should the default for units) we can choose:
Kilobits per second
Kilobytes per second
Megabits per second
Megabytes per second

Am 24.06.2015 10:47, schrieb Rade Martinović:

**Comment by arlake228** [comment]
Is this work complete or should we move it to a later release?

**Comment by laeti-tia** [comment]
This is not done yet, we need to move it to later.

**Comment by laeti-tia** [comment]
Rade, Hakan, can you propose a schema change/extension that would fit both of you?

**Comment by HakanCalimFau** [comment]
OK I started the iperf3 support. I setup iperf3 as a standart setting so every measurement will done with iperf3. In case of iperf oppd returns measurement information as known. No iperf3 fields will be visible.
In case of iperf3 I introduced this fileds:
lineType to distinguish if information is normal or summary
retransmits the Retr field in the iperf3 output
sndcwdValue the value of Cwd field
sndcwdType the type of Ced
nodeType will be visible if lineType is summary. Value can be receiver or sender.

so a data line will look like:
ns7:datum lineType="data" numBytes="18.5" value="77.5" valueUnits="Mbits/sec" sndcwdValue="1.62" timeValue="1445434940" interval="4.00-6.00" numBytesUnits="MBytes" timeType="unix" retransmits="0" sndcwdType="MBytes"/>

and a summary line will look like:
<ns7:datum nodeType="sender" lineType="summary" numBytes="100" value="70.3" valueUnits="Mbits/sec" timeValue="1445434940" interval="0.00-12.00" numBytesUnits="MBytes" timeType="unix" retransmits="0"/>
<ns7:datum nodeType="receiver" lineType="summary" numBytes="100" value="70.3" valueUnits="Mbits/sec" timeValue="1445434940" interval="0.00-12.00" numBytesUnits="MBytes" timeType="unix" retransmits=""/>

@Rade is this ok for you or do you need any other information?

**Comment by RockyMM** [comment]
@HakanCalimFau I am sorry Hakan, I don't see summary line.

I cannot commit myself to this issue until later next week so please wait until then for my feedback.

**Comment by RockyMM** [comment]
@HakanCalimFau "lineType" is a bit misleading. I would like the attribute to be called something that would communicate its _purpose_ better. Let's call it "measurementType" or just "type". What do you think?

**Comment by RockyMM** [comment]
@HakanCalimFau - BTW, where is the current source code of OPPD?

**Comment by laeti-tia** [comment]
@RockyMM OPPD source code is stored here in github Rade.  But I guess that changes to better support iperf3 as described here have not yet been commited/pushed by Hakan.

@HakanCalimFau Can you submit your code already written here, even if it is not complete yet doesn't really matter, it mainly is for Rade to see.  If you prefer, so not to break the current OPPD packages, you can also put it in a separate branch.  Thank you!

**Comment by HakanCalimFau** [comment]
OK commited. You can find the names in BWCTL.pm module. I have also now the first version of iperf3 support running. This MP is added in psUI (test version) as RRZE Hakan Dev. You can request from there measurements and can see in result iperf3 fields if available.

**Comment by arlake228** [comment]
@HakanCalimFau can we close this? Looks like support has been added based on last comment.

**Comment by laeti-tia** [comment]
Yes, we can close it.

**Comment by HakanCalimFau** [comment]
Yes it can be closed. Thanks.
