### ISSUE TITLE
OPPD support for multi-homing

### ISSUE THREAD

**Issue by igarny** [perfsonar/oppd#4]
Hi Hakan,

Here is what I see in the logs:
2015/07/20 15:45:07 <INFO> perfSONAR.MP.BWCTL - Service: MP/BWCTL called with command: bwctl -s 62.40.123.106 -c 62.40.106.195 -i 5 -t 15
2015/07/20 15:45:09 <ERROR> perfSONAR.MP.BWCTL - bwctl: Unable to connect to 62.40.106.195

The problem is that with multi-home systems you should always account for -B switch with the IP of the local interface:

The command should be:

bwctl -s 62.40.123.106 -B 62.40.123.106 -c 62.40.106.195 -i 5 -t 15

Please note that I have no idea where the command is being formed, whether pS UI or OPPD.

Please consider checking OWAMP tests as well.

Currently this is breaking tests in GEANT (testing).

Best regards,
Ivan

**Comment by HakanCalimFau** [comment]
Hi Ivan,

I can add the the -B option as localaddress parameter to schema. You can add this parameter to your request message like:
<nmwg:parameter name="localaddress" value="192.168.1.2"/>

In owping I didn't found such a parameter. If you know the name of the same option please let me know!

Thanks and with best regards,
Hakan

**Comment by igarny** [comment]
Hi Hakan,

The option with owping is -S

**Comment by RockyMM** [comment]
Just to inform everyone that no commands are formed in psUI :smile:

**Comment by laeti-tia** [comment]
Hi Ivan,

Why is there the need to use the `-B` option?  Why was it working in the past without it and not working any more now?

Thanks,

**Comment by igarny** [comment]
Hi Antoine, Rade,

This is what I have tested as a command. I am not sure how far in the past you are looking, but it is a requirement in order to be able to run measurements with multi-interface perfSONAR toolkits.
I am unsure about your doubts and the why questions. It is the current and future reality with multi-interface perfSONAR toolkits.
      -B, --local_address srcaddr
              Bind  the local address of the client socket to srcaddr. srcaddr
              can be specified using a DNS  name  or  using  standard  textual
              notations for the IP addresses.

```
          Default:
                 Unspecified (wild-card address selection).
```

@Rade: I had it discussed with Hakan on 22.07 (yesterday) and did explain him how to form the request with the information he currently receives as a request from pS UI. No requirements towards pS UI are foreseen for this specific improvement.

Best regards,
Ivan

**Comment by laeti-tia** [comment]
Ok, so can I rephrase your request as a requirement for OPPD to support the multi-interface/multi-homing capabilities of BWCTL and OWAMP?

**Comment by RockyMM** [comment]
I'm on a short vacation but I still wanted to join the discussion.

I think that this feature is what Pavle required from pS toolkit in order to run multi homing measurements. This will probably get pS toolkit a step closer to integration with MDVPN tool Pavle developed last year. Maybe we could inform him about this change?

**Comment by laeti-tia** [comment]
> I think that this feature is what Pavle required from pS toolkit in order to run multi homing measurements. This will probably get pS toolkit a step closer to integration with MDVPN tool Pavle developed last year. Maybe we could inform him about this change?

To my understanding the SQM solution developed by Pavle and his team is not using OPPD but OWAMP directly.

Antoine.

**Comment by RockyMM** [comment]
> To my understanding the SQM solution developed by Pavle and his team is not using OPPD but OWAMP directly.

You are completely right. Back when GN3+ was starting, there were comments from Pavle how and if pS toolkit could be used. If this was supported back then, maybe they would have implemented their solution differently. This feature would allow them to trigger multi-homed OWAMP measurements remotely. 

But I now it's no longer relevant.

Sorry for making unneeded noise :)
