### ISSUE TITLE
OPPD packages contain outdated code.

### ISSUE THREAD

**Issue by igarny** [perfsonar/oppd#5]
Hi guys,

Please note that even before the update from Hakan today, the code in OPPD lib was 9 months old. My problem was and respectively still is that there is a functionality missing or failing on current rpm release 3.4-2. The improvements are enabling on-demand measurements on hosts with multiple interfaces.
Function CheckIPislocal was missing in 3.4-2 even though was here beforehand. Nevertheless in cooperation with Hakan, I managed to produce some tests and we found that there was still room for improvement.

Now the current code is tested and found to be working on environment with multiple interfaces for both BWCTL and OWAMP.

Please produce RPM packages from the code and update the Internet2 repository.

Best regards.
Ivan

**Comment by laeti-tia** [comment]
This will be part of the 3.5 release.  I'm not sure it still makes sense to port back changes to the 3.4 packages.
